// Currency mapping and formatting utilities

export const CURRENCY_SYMBOLS: { [key: string]: string } = {
  USD: "$",
  EUR: "€",
  ETB: "Br",
  SOS: "SOS",
  JPY: "¥",
  GBP: "£",
  KES: "KSh",
  TZS: "TSh",
  UGX: "USh",
  RWF: "RF",
  BIF: "FBu",
  DJF: "Fdj",
  ERN: "Nfk",
  AED: "د.إ",
  SAR: "﷼",
  QAR: "﷼",
  KWD: "د.ك",
  BHD: ".د.ب",
  OMR: "﷼",
  JOD: "د.ا",
  LBP: "ل.ل",
  SYP: "£S",
  IQD: "ع.د",
  IRR: "﷼",
  AFN: "؋",
  PKR: "₨",
  INR: "₹",
  BDT: "৳",
  LKR: "₨",
  NPR: "₨",
  BTN: "Nu.",
  MYR: "RM",
  SGD: "S$",
  THB: "฿",
  VND: "₫",
  IDR: "Rp",
  PHP: "₱",
  CNY: "¥",
  HKD: "HK$",
  TWD: "NT$",
  KRW: "₩",
  CAD: "C$",
  AUD: "A$",
  NZD: "NZ$",
  CHF: "CHF",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "zł",
  CZK: "Kč",
  HUF: "Ft",
  RON: "lei",
  BGN: "лв",
  HRK: "kn",
  RSD: "дин",
  TRY: "₺",
  RUB: "₽",
  UAH: "₴",
  BYN: "Br",
  MDL: "lei",
  GEL: "₾",
  AMD: "֏",
  AZN: "₼",
  KZT: "₸",
  UZS: "soʻm",
  TJS: "ЅМ",
  KGS: "лв",
  TMT: "T",
  MNT: "₮",
  BRL: "R$",
  ARS: "$",
  CLP: "$",
  COP: "$",
  PEN: "S/",
  UYU: "$U",
  BOB: "Bs.",
  PYG: "₲",
  VES: "Bs.S",
  GYD: "GY$",
  SRD: "Sr$",
  FKP: "£",
  MXN: "$",
  GTQ: "Q",
  BZD: "BZ$",
  SVC: "$",
  HNL: "L",
  NIO: "C$",
  CRC: "₡",
  PAB: "B/.",
  CUP: "$",
  DOP: "RD$",
  HTG: "G",
  JMD: "J$",
  KYD: "CI$",
  TTD: "TT$",
  BBD: "Bds$",
  XCD: "$",
  AWG: "ƒ",
  ANG: "ƒ",
  BMD: "$",
  BSD: "B$",
  MAD: "د.م.",
  DZD: "د.ج",
  TND: "د.ت",
  LYD: "ل.د",
  EGP: "£E",
  SDG: "ج.س.",
  SSP: "£",
  ZAR: "R",
  NAD: "N$",
  BWP: "P",
  SZL: "E",
  LSL: "M",
  MWK: "MK",
  ZMW: "ZK",
  AOA: "Kz",
  MZN: "MT",
  MGA: "Ar",
  KMF: "CF",
  SCR: "₨",
  MUR: "₨",
  MVR: "Rf",
  XOF: "CFA",
  XAF: "FCFA",
  GHS: "₵",
  NGN: "₦",
  SLL: "Le",
  LRD: "L$",
  CIV: "CFA",
  GMD: "D",
  GNF: "FG",
  MLI: "CFA",
  BFA: "CFA",
  NER: "CFA",
  TCD: "CFA",
  CMR: "CFA",
  CAF: "CFA",
  GNQ: "CFA",
  GAB: "CFA",
  COG: "CFA",
  STP: "Db",
  CVE: "$"
};

export const formatPrice = (price: number | string, currency: string = 'USD'): string => {
  const numericPrice = typeof price === 'string' ? parseFloat(price) : price;
  
  if (isNaN(numericPrice)) return 'Price not available';
  
  const symbol = CURRENCY_SYMBOLS[currency.toUpperCase()] || currency.toUpperCase();
  
  // Format with appropriate decimal places
  const formattedAmount = numericPrice.toLocaleString(undefined, {
    minimumFractionDigits: currency.toUpperCase() === 'JPY' ? 0 : 2,
    maximumFractionDigits: currency.toUpperCase() === 'JPY' ? 0 : 2
  });
  
  // Some currencies show symbol after amount
  const suffixCurrencies = ['ETB', 'SOS', 'KSh', 'TSh', 'USh', 'RF', 'FBu', 'Fdj', 'Nfk'];
  
  if (suffixCurrencies.includes(currency.toUpperCase())) {
    return `${formattedAmount} ${symbol}`;
  }
  
  return `${symbol}${formattedAmount}`;
};

export const getCurrencySymbol = (currency: string): string => {
  return CURRENCY_SYMBOLS[currency.toUpperCase()] || currency.toUpperCase();
};