import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";

interface CurrencySelectorProps {
  selectedCurrency: string;
  onCurrencyChange: (value: string) => void;
}

const currencies = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "GBP", name: "British Pound" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "INR", name: "Indian Rupee" },
  { code: "AED", name: "UAE Dirham" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "ZAR", name: "South African Rand" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "DKK", name: "Danish Krone" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "RON", name: "Romanian Leu" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "TMT", name: "Turkmenistani Manat" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "MMK", name: "Myanmar Kyat" },
  { code: "THB", name: "Thai Baht" },
  { code: "LAK", name: "Lao Kip" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "KRW", name: "South Korean Won" },
  { code: "KPW", name: "North Korean Won" },
  { code: "MNT", name: "Mongolian Tugrik" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "TWD", name: "Taiwan New Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "PGK", name: "Papua New Guinean Kina" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "VUV", name: "Vanuatu Vatu" },
  { code: "TOP", name: "Tongan Pa'anga" },
  { code: "WST", name: "Samoan Tala" },
  { code: "KI", name: "Kiribati Dollar" },
  { code: "TVD", name: "Tuvalu Dollar" },
  { code: "NRU", name: "Nauru Dollar" },
  { code: "MHL", name: "Marshall Islands Dollar" },
  { code: "FSM", name: "Micronesian Dollar" },
  { code: "PLW", name: "Palauan Dollar" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "COP", name: "Colombian Peso" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "PYG", name: "Paraguayan Guarani" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "VES", name: "Venezuelan Bolívar" },
  { code: "GYD", name: "Guyanese Dollar" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "SVC", name: "Salvadoran Colón" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "CVE", name: "Cape Verdean Escudo" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "ERN", name: "Eritrean Nakfa" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "BIF", name: "Burundian Franc" },
  { code: "MWK", name: "Malawian Kwacha" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWL", name: "Zimbabwean Dollar" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "AOA", name: "Angolan Kwanza" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "BWP", name: "Botswanan Pula" },
  { code: "SZL", name: "Swazi Lilangeni" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "SCR", name: "Seychellois Rupee" }
];

export const CurrencySelector = ({ selectedCurrency, onCurrencyChange }: CurrencySelectorProps) => {
  return (
    <div className="space-y-2">
      <Label htmlFor="currency">Currency</Label>
      <Select value={selectedCurrency} onValueChange={onCurrencyChange}>
        <SelectTrigger className="glass-button border-white/30">
          <SelectValue placeholder="Select currency" />
        </SelectTrigger>
        <SelectContent className="bg-white border border-gray-200 shadow-lg max-h-60">
          {currencies.map((currency) => (
            <SelectItem key={currency.code} value={currency.code} className="hover:bg-gray-100">
              {currency.code} - {currency.name}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
};